
package GUI.citas;

import GUI.Main;
import barberia.Cita;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VerCalendario extends javax.swing.JFrame {

    public static final int SEMANA = 0;
    public static final int MES = 1;
    private ArrayList<Cita> citas;
    private LocalDateTime fechaInicio;
    
    public VerCalendario(Main main, int modo, LocalDateTime fechaInicio) {
        try{
            if (main.getBarberia().getCitas().size()==0){
                throw new RuntimeException("No hay citas aún");
            }
        initComponents();
        this.fechaInicio = fechaInicio;
        this.setVisible(true);
       
        if (modo == SEMANA){
            citas = main.getBarberia().getAgenda().getCitasSemana(fechaInicio);
        }else{
            citas = main.getBarberia().getAgenda().getCitasMes(fechaInicio);
            System.out.println(citas.size());
        }
        initTabla();
        }
        catch(RuntimeException e){
            JOptionPane.showMessageDialog(this, "No ha creado citas", "No hay citas", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    private void initTabla(){
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
       
                return false;
            }
        };
        
        modelo.addColumn("Fecha");
        modelo.addColumn("Cliente");
        modelo.addColumn("Correo");
        DateTimeFormatter dt =DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        try{    
        for (Cita c : citas){
            modelo.addRow(new Object[] {c.getFecha().format(dt), c.getCliente().getNombre(), c.getCliente().getCorreo()});
        }
        }
        catch (NullPointerException e){
            
        }
        jTable1.setModel(modelo);
                
                
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
